from __future__ import annotations

from typing import Optional, Tuple, Union, Literal

import numpy as np
import networkx as nx


class GraphSampler:
    """
    Utility class for generating random DAGs.

    Acyclicity is ensured by sampling edges only from earlier to later nodes in
    a random topological order (random permutation).
    """

    def __init__(self, seed: Optional[int] = None, graph_type: Literal["erdos_renyi", "gnr"] = "erdos_renyi") -> None:
        """
        Parameters
        ----------
        seed : int, optional
            Seed used for reproducibility.
        graph_type : Literal["erdos_renyi", "gnr"], default "erdos_renyi"
            The type of graph to generate.

        Notes
        -----
        *erdos_renyi*
        Erdos-Renyi DAGs are generated by ...
        
        
        *gnr*
        At each step a new node is added. It picks a random existing node *v*
        uniformly at random; with probability `r` the edge is *redirected* to
        the parent of *v* (the node *v* points to), otherwise it connects
        directly to *v*. This redirection mechanism produces preferential
        attachment and yields scale-free in-degree distributions.

        Acyclicity is guaranteed by construction: every new node only creates
        an edge pointing to an *older* node.
        """
        self.rng = np.random.default_rng(seed)
        self.sample_dag = {
            "erdos_renyi": self.sample_erdos_renyi, 
            "gnr": self.sample_gnr,
        }[graph_type]


    def sample_erdos_renyi(
        self,
        num_nodes: int,
        p: float,
        return_perm: bool = False,
    ) -> Union[nx.DiGraph, Tuple[nx.DiGraph, np.ndarray]]:
        """
        Create a random DAG using Erdos-Renyi model.

        Parameters
        ----------
        num_nodes : int
            Number of nodes.
        p : float
            Probability of an edge between any ordered pair (i < j) in a random
            topological order. Must be in [0, 1].
        return_perm : bool, default False
            If True, also return the permutation (topological order) used.

        Returns
        -------
        G : nx.DiGraph
            The generated DAG with nodes labeled 0..num_nodes-1.
        perm : np.ndarray, optional
            The permutation used (only if `return_perm=True`).
        """
        n = int(num_nodes)
        if n < 0:
            raise ValueError("num_nodes must be non-negative.")
        if not (0.0 <= p <= 1.0):
            raise ValueError("p must be in [0, 1].")

        G = nx.DiGraph()
        G.add_nodes_from(range(n))

        if n <= 1 or p == 0.0:
            return (G, np.arange(n)) if return_perm else G

        # Random topological order
        perm = self.rng.permutation(n)

        # Strictly upper-triangular Bernoulli mask (acyclic by construction)
        mask = np.triu(self.rng.random((n, n)) < p, k=1)

        # Extract and add edges
        i_idx, j_idx = np.nonzero(mask)
        if i_idx.size:
            src = perm[i_idx]
            dst = perm[j_idx]
            G.add_edges_from(zip(src.tolist(), dst.tolist()))

        return (G, perm) if return_perm else G
    

    def sample_gnr(
        self,
        num_nodes: int,
        p: float,
        return_order: bool = False,
    ) -> Union[nx.DiGraph, Tuple[nx.DiGraph, np.ndarray]]:
        """
        Create a random scale-free DAG via Growing Network with Redirection.

        Each new node *t* (added in order 1, 2, …, n-1):
          1. Picks an existing node *v* uniformly at random.
          2. With probability *p*, redirects the edge to the (unique)
             out-neighbour of *v* (i.e. the node *v* itself points to).
             If *v* has no out-neighbour, the edge stays at *v*.
          3. Adds a directed edge from the new node *t* → target.

        Because edges always point from a newer node to an older node the
        resulting graph is a DAG by construction.

        After construction the node labels are randomly permuted so that the
        topological order is not trivially encoded in the labels.

        Parameters
        ----------
        num_nodes : int
            Number of nodes (n ≥ 0).
        p : float
            Edge probability. Must be in [0, 1].
            * p = 0  → no edges (empty graph).
            * p → 1  → dense graph.
        return_order : bool, default False
            If True, also return the permutation that maps the original
            arrival order to the final node labels.

        Returns
        -------
        G : nx.DiGraph
            The generated DAG with nodes labelled 0 … num_nodes-1.
        perm : np.ndarray, optional
            perm[i] is the final label of the node that arrived at step *i*
            (only returned when ``return_order=True``).
        """
        n = int(num_nodes)
        if n < 0:
            raise ValueError("num_nodes must be non-negative.")
        if not (0.0 <= p <= 1.0):
            raise ValueError("p must be in [0, 1].")

        G = nx.DiGraph()
        G.add_nodes_from(range(n))

        if n <= 1:
            perm = np.arange(n)
            return (G, perm) if return_order else G

        # ----- GNR growth process (arrival-order labels 0 … n-1) ---------
        # parent[t] stores the single out-neighbour of node t (or -1 if none)
        parent = np.full(n, -1, dtype=np.intp)
        edges: list[tuple[int, int]] = []

        for t in range(1, n):
            # Step 1: pick a random existing node
            v = int(self.rng.integers(0, t))

            # Step 2: with probability p, redirect to v's parent
            if self.rng.random() < p and parent[v] != -1:
                target = parent[v]
            else:
                target = v

            # Step 3: edge from new node t → target (always newer → older)
            parent[t] = target
            edges.append((t, target))

        # ----- Random relabelling so topology isn't obvious from IDs ------
        perm = self.rng.permutation(n)  # perm[arrival_order] = final_label
        relabelled_edges = [(int(perm[s]), int(perm[d])) for s, d in edges]
        G.add_edges_from(relabelled_edges)

        return (G, perm) if return_order else G
