from __future__ import annotations

from typing import Optional, Tuple, Union, Literal

import numpy as np
import networkx as nx


class GraphSampler:
    """
    Utility class for generating random DAGs.

    Acyclicity is ensured by sampling edges only from earlier to later nodes
    in a random topological order (random permutation).
    """

    def __init__(
        self,
        seed: Optional[int] = None,
        graph_type: Literal["erdos_renyi", "gnr", "cauchy"] = "erdos_renyi",
    ) -> None:
        """
        Parameters
        ----------
        seed : int, optional
            Seed used for reproducibility.
        graph_type : Literal["erdos_renyi", "gnr", "cauchy"],
                     default "erdos_renyi"
            The type of graph to generate.

        Notes
        -----
        *erdos_renyi*
        Erdos-Renyi DAGs are generated by sampling each forward edge
        independently with a fixed probability p.

        *gnr*
        At each step a new node is added. It picks a random existing node *v*
        uniformly at random; with probability `r` the edge is *redirected* to
        the parent of *v* (the node *v* points to), otherwise it connects
        directly to *v*. This redirection mechanism produces preferential
        attachment and yields scale-free in-degree distributions.

        Acyclicity is guaranteed by construction: every new node only creates
        an edge pointing to an *older* node.

        *cauchy*
        For node indices i < j in a random topological order, an edge is
        placed with probability p_ij = sigmoid(A + B_i + C_j), where A, B_i,
        C_j are independent standard Cauchy random variables. A controls the
        general level of connectivity, while B_i and C_j control the
        individual outgoing and incoming connectivities of the nodes,
        respectively. The heavy tails of the Cauchy distribution yield more
        diverse connectivity patterns than independent Bernoulli probabilities.
        """
        self.rng = np.random.default_rng(seed)
        self.sample_dag = {
            "erdos_renyi": self.sample_erdos_renyi,
            "gnr": self.sample_gnr,
            "cauchy": self.sample_cauchy,
        }[graph_type]

    def sample_erdos_renyi(
        self,
        num_nodes: int,
        p: float,
        return_perm: bool = False,
    ) -> Union[nx.DiGraph, Tuple[nx.DiGraph, np.ndarray]]:
        """
        Create a random DAG using Erdos-Renyi model.

        Parameters
        ----------
        num_nodes : int
            Number of nodes.
        p : float
            Probability of an edge between any ordered pair (i < j) in a random
            topological order. Must be in [0, 1].
        return_perm : bool, default False
            If True, also return the permutation (topological order) used.

        Returns
        -------
        G : nx.DiGraph
            The generated DAG with nodes labeled 0..num_nodes-1.
        perm : np.ndarray, optional
            The permutation used (only if `return_perm=True`).
        """
        n = int(num_nodes)
        if n < 0:
            raise ValueError("num_nodes must be non-negative.")
        if not (0.0 <= p <= 1.0):
            raise ValueError("p must be in [0, 1].")

        G = nx.DiGraph()
        G.add_nodes_from(range(n))

        if n <= 1 or p == 0.0:
            return (G, np.arange(n)) if return_perm else G

        # Random topological order
        perm = self.rng.permutation(n)

        # Strictly upper-triangular Bernoulli mask (acyclic by construction)
        mask = np.triu(self.rng.random((n, n)) < p, k=1)

        # Extract and add edges
        i_idx, j_idx = np.nonzero(mask)
        if i_idx.size:
            src = perm[i_idx]
            dst = perm[j_idx]
            G.add_edges_from(zip(src.tolist(), dst.tolist()))

        return (G, perm) if return_perm else G

    def sample_gnr(
        self,
        num_nodes: int,
        p: float,
        return_order: bool = False,
    ) -> Union[nx.DiGraph, Tuple[nx.DiGraph, np.ndarray]]:
        """
        Create a random scale-free DAG via Growing Network with Redirection.

        Each new node *t* (added in order 1, 2, …, n-1):
          1. Picks an existing node *v* uniformly at random.
          2. With probability *p*, redirects the edge to the (unique)
             out-neighbour of *v* (i.e. the node *v* itself points to).
             If *v* has no out-neighbour, the edge stays at *v*.
          3. Adds a directed edge from the new node *t* → target.

        Because edges always point from a newer node to an older node the
        resulting graph is a DAG by construction.

        After construction the node labels are randomly permuted so that the
        topological order is not trivially encoded in the labels.

        Parameters
        ----------
        num_nodes : int
            Number of nodes (n ≥ 0).
        p : float
            Redirection probability. Must be in [0, 1].
            * p = 0  → random recursive tree (uniform attachment).
            * p → 1  → stronger preferential attachment / more scale-free.
        return_order : bool, default False
            If True, also return the permutation that maps the original
            arrival order to the final node labels.

        Returns
        -------
        G : nx.DiGraph
            The generated DAG with nodes labelled 0 … num_nodes-1.
        perm : np.ndarray, optional
            perm[i] is the final label of the node that arrived at step *i*
            (only returned when ``return_order=True``).
        """
        if num_nodes < 0:
            raise ValueError("num_nodes must be non-negative.")
        if not (0.0 <= p <= 1.0):
            raise ValueError("p must be in [0, 1].")

        if num_nodes <= 1:
            G = nx.DiGraph()
            G.add_nodes_from(range(num_nodes))
            perm = np.arange(num_nodes)
            return (G, perm) if return_order else G

        seed = int(self.rng.integers(0, 2**31))
        G_raw = nx.gnr_graph(num_nodes, p, seed=seed)

        # Extract and add edges mapped through the random permutation
        # perm[i] = label assigned to arrival-order position i,
        perm = self.rng.permutation(num_nodes)

        G = nx.DiGraph()
        G.add_nodes_from(range(num_nodes))
        for u, v in G_raw.edges():
            G.add_edge(perm[u], perm[v])

        return (G, perm) if return_order else G

    def sample_cauchy(
        self,
        num_nodes: int,
        p: float,
        return_perm: bool = False,
    ) -> Union[nx.DiGraph, Tuple[nx.DiGraph, np.ndarray]]:
        """
        Create a random DAG using the Cauchy-logit model.

        For node indices i < j in a random topological order, an edge is
        placed with probability::

            p_ij = sigmoid(A + B_i + C_j)

        where A, B_i, C_j are independent standard Cauchy random variables.

        * **A** controls the overall level of connectivity.
        * **B_i** controls the outgoing connectivity of node *i*.
        * **C_j** controls the incoming connectivity of node *j*.

        The heavy tails of the Cauchy distribution produce more diverse
        connectivity patterns than a single shared Bernoulli probability:
        some nodes become hubs while others remain nearly isolated, and
        "exceptions to the rule" (unexpected edges or non-edges) are more
        likely.

        Parameters
        ----------
        num_nodes : int
            Number of nodes (n ≥ 0).
        p : float
            Should be -1, implemented for compatibility with other graph samplers but ignored since the Cauchy-logit model does not use a single edge probability parameter.
        return_perm : bool, default False
            If True, also return the permutation (topological order) used.

        Returns
        -------
        G : nx.DiGraph
            The generated DAG with nodes labelled 0 … num_nodes-1.
        perm : np.ndarray, optional
            The permutation used (only if ``return_perm=True``).
        """
        assert p == -1., f"The Cauchy-logit model does not use a single edge probability parameter, so p should be -1., but got {p = }."
        n = int(num_nodes)
        if n < 0:
            raise ValueError("num_nodes must be non-negative.")

        G = nx.DiGraph()
        G.add_nodes_from(range(n))

        if n <= 1:
            return (G, np.arange(n)) if return_perm else G

        # Random topological order
        perm = self.rng.permutation(n)

        # Independent standard Cauchy draws
        A = self.rng.standard_cauchy()          # scalar – global connectivity
        B = self.rng.standard_cauchy(n)         # per-node outgoing bias
        C = self.rng.standard_cauchy(n)         # per-node incoming bias

        # Build the strictly upper-triangular logit matrix
        # logit_ij = A + B[i] + C[j]  for i < j
        # Using broadcasting: B[:, None] + C[None, :] is (n, n)
        logits = A + B[:, None] + C[None, :]   # (n, n)

        # Edge probabilities via the sigmoid (logistic) function
        # sigmoid(x) = 1 / (1 + exp(-x))
        probs = 1.0 / (1.0 + np.exp(-logits))  # (n, n)

        # Sample edges only in the upper triangle (i < j) for acyclicity
        uniform = self.rng.random((n, n))
        mask = np.triu(uniform < probs, k=1)

        # Extract and add edges mapped through the random permutation
        i_idx, j_idx = np.nonzero(mask)
        if i_idx.size:
            src = perm[i_idx]
            dst = perm[j_idx]
            G.add_edges_from(zip(src.tolist(), dst.tolist()))

        return (G, perm) if return_perm else G
